title = "Technically some technical stuff."
baseurl = "https://technically.kakwalab.ovh/"
baseURL = "https://technically.kakwalab.ovh/"
languageCode = "en"
theme = "kpoison"
copyright = "&copy; <a href=\"https://github.com/kakwa\">Pierre-Francois Carpentier</a> 2025"
googleAnalytics = ""
enableRobotsTXT = false

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Pierre-François Carpentier" # Author full name
authorEmail = "carpentier.pf@gmail.com" # Author email

[params.author]
name = "Pierre-François Carpentier"
email = "carpentier.pf@gmail.com"
bio = "Just another geek who likes to build stuff, from cloud infrastructure to 3D printers."

[params.assets]
customCSS = ["css/custom.css"]
googleFonts = []

[params.info]
enableSocial = true # Adds OpenGraph and Twitter cards
poweredby = false # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = false # Add copy button above code blocks
taxonomiesCount = true # Add taxonomies count

[params.features]
disqusOnDemand = false  # Load Disqus comments on click
mathjax = false
katex = false

[markup]
[markup.tableOfContents]
startLevel = 1
endLevel = 2
ordered = true

[params]
# Site-wide params (PaperMod)
description = "Just another geek who likes to build stuff and write about it"
defaultTheme = "auto"
disableThemeToggle = false
ShowToc = true
TocOpen = true
ShowBreadCrumbs = true
ShowReadingTime = true
showCodeCopyButtons = true

# Theme (kpoison/poison) specific params
brand = "Kakwa's Blog"
# Use local image from static directory
brand_image = "/author.png"
favicon = "favicon-32x32.png"
dark_mode = true
front_page_content = ["posts"]

# Sidebar/menu
menu = [
    {Name = "Blog Posts", URL = "/posts/"},
    {Name = "Other Links", External = true, URL = ""},
    {Name = "Software Projects", External = true, URL = "https://github.com/kakwa?tab=repositories&q=&type=&language=&sort=stargazers", HasChildren = false},
    {Name = "3D Printing Models", External = true, URL = "https://www.printables.com/@kakwa_3337391/models", HasChildren = false},
    {Name = "Photos", External = true, URL = "https://lens.kakwalab.ovh/", HasChildren = false},
    {Name = "Projects I like", External = true, URL = "/projects-i-like/"},
]

# Social links (used by theme)
github_url = "https://github.com/kakwa"
mastodon_url = "https://mastodon.social/@kakwa_"
linkedin_url = "https://www.linkedin.com/in/pfcarpentier"
email_url = "mailto:carpentier.pf@gmail.com"
rss_icon = true
rss_section = "posts"

# Color tweaks: replace black with dark grey, white with slightly beige
# Sidebar colors
moon_sun_background_color = "#515151"
moon_sun_color = "#EDE7DB"              # was #FFF
sidebar_a_color = "#EDE7DB"             # was #FFF
sidebar_bg_color = "#202020"
sidebar_h1_color = "#EDE7DB"            # was #FFF
sidebar_img_border_color = "#515151"
sidebar_p_color = "#909090"
sidebar_socials_color = "#EDE7DB"       # was #FFF

# Light mode content colors
code_color = "#303030"                   # was #000
code_background_color = "#E0E0E0"
code_block_color = "#F5F2E8"            # was #FFF
code_block_background_color = "#272822"
content_bg_color = "#F5F2E8"            # slightly beige
date_color = "#515151"
link_color = "#268BD2"
list_color = "#5A5A5A"
post_title_color = "#303030"            # was darker/black
table_border_color = "#E3E0D8"          # subtle beige tint
table_stripe_color = "#F0ECE3"
text_color = "#303030"                  # was near black

# Dark mode content colors
code_color_dark = "#EDE7DB"             # was #FFF
code_background_color_dark = "#515151"
code_block_color_dark = "#EDE7DB"       # was #FFF
code_block_background_color_dark = "#272822"
content_bg_color_dark = "#1A1A1A"       # dark grey instead of near black
date_color_dark = "#9A9A9A"
link_color_dark = "#268BD2"
list_color_dark = "#9D9D9D"
post_title_color_dark = "#EDE7DB"
table_border_color_dark = "#515151"
table_stripe_color_dark = "#1E1E1E"
text_color_dark = "#EDE7DB"             # was #EEE/white

[params.social]
mastodon = "mastodon.social/@kakwa_"
github = "kakwa"
email = "carpentier.pf@gmail.com"
linkedin = "pfcarpentier"
rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
platforms = ["github", "mastodon", "linkedin"]

 

[taxonomies]
tag ="tags"
