title = "Technically some technical stuff."
baseurl = "https://technically.kakwalab.ovh/"
baseURL = "https://technically.kakwalab.ovh/"
languageCode = "en"
theme = "beautifulhugo"
copyright = "&copy; <a href=\"https://github.com/kakwa\">Pierre-Francois Carpentier</a> 2024"
googleAnalytics = ""
enableRobotsTXT = true

[params.rss] # Adding this tag enables RSS feed
includeContent = false # Includes whole content in rss
authorName = "Pierre-François Carpentier" # Author full name
authorEmail = "carpentier.pf@gmail.com" # Author email

[params.author]
name = "Pierre-François Carpentier"
email = "carpentier.pf@gmail.com"
bio = "Just another geek who likes to build stuff, from cloud infrastructure to 3D printers."

[params.assets]
customCSS = ["css/custom.css"]
googleFonts = []

[params.info]
enableSocial = true # Adds OpenGraph and Twitter cards
poweredby = false # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = false # Add copy button above code blocks
taxonomiesCount = true # Add taxonomies count

[params.features]
disqusOnDemand = false  # Load Disqus comments on click
mathjax = false
katex = false

[markup]
[markup.tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 1

[params.social]
mastodon = "mastodon.instance/@kakwa"
github = "kakwa"
email = "carpentier.pf@gmail.com"
linkedin = "pfcarpentier"
rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
platforms = ["github", "mastodon", "linkedin"]

[params]
selfHosted = true
mainSections = ["post", "posts"]

[taxonomies]
tag ="tags"
